logging:
  level:
    root: info
    com.sisipapa.springbatch.batch: debug

spring:
  batch:
    job:
      names: ${job.name:NONE}
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/test_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: password


